### ISSUE TITLE
[VITE_ERROR] virtual:nuxt:shiki-config.mjs

### ISSUE THREAD

**Issue by justin-schroeder** [pi0/nuxt-shiki#12]
Hi 👋

Fresh install of nuxt-shiki (0.1.1) + fresh install of nuxt (3.10.2) seem to error out:

![image](https://github.com/pi0/nuxt-shiki/assets/1950463/f3a702e1-8a65-42d4-b1ef-7ad33ce03d9c)

Full reproduction repository here:

https://github.com/justin-schroeder/shiki-nuxt-reproduction

**Comment by pi0** [comment]
Should be solved in latest release thanks for report!
